version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres-spring-security
    restart: always
    environment:
      POSTGRES_DB: spring_security
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_spring-security
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "15432:80"  # você acessa o pgAdmin em http://localhost:15432
    networks:
      - backend

  app:
    build: .
    container_name: spring_security-app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/spring_security
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge