# # version: "3.8"

# # services:
# #   mysql:
# #     image: mysql:8.0
# #     container_name: mysql-spring-security
# #     restart: always
# #     environment:
# #       MYSQL_DATABASE: spring_security
# #       MYSQL_ROOT_PASSWORD: root
# #       MYSQL_USER: root
# #       MYSQL_PASSWORD: root
# #     ports:
# #       - "3306:3306"
# #     volumes:
# #       - mysql_data:/var/lib/mysql
# #     command: --default-authentication-plugin=mysql_native_password

# #   phpmyadmin:
# #     image: phpmyadmin/phpmyadmin
# #     container_name: phpmyadmin
# #     restart: always
# #     environment:
# #       PMA_HOST: mysql
# #       PMA_PORT: 3306
# #       MYSQL_ROOT_PASSWORD: root
# #     ports:
# #       - "8081:80"
# #     depends_on:
# #       - mysql

# #   app:
# #     build: .
# #     container_name: springboot-app
# #     restart: always
# #     depends_on:
# #       - mysql
# #     ports:
# #       - "8080:8080"
# #     environment:
# #       SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/demo_security?useTimezone=true&serverTimezone=America/Sao_Paulo&useSSL=false
# #       SPRING_DATASOURCE_USERNAME: root
# #       SPRING_DATASOURCE_PASSWORD: root
# #     networks:
# #       - backend

# # volumes:
# #   mysql_data:

# # networks:
# #   backend:

# # version: "3.8"

# # services:
# #   mysql:
# #     image: mysql:8.0
# #     container_name: mysql-spring-security
# #     restart: always
# #     environment:
# #       MYSQL_DATABASE: demo_security
# #       MYSQL_ROOT_PASSWORD: root
# #     ports:
# #       - "3306:3306"
# #     volumes:
# #       - mysql_data:/var/lib/mysql
# #     command: --default-authentication-plugin=mysql_native_password
# #     networks:
# #       - backend

# #   phpmyadmin:
# #     image: phpmyadmin/phpmyadmin
# #     container_name: phpmyadmin
# #     restart: always
# #     environment:
# #       PMA_HOST: mysql
# #       PMA_PORT: 3306
# #       MYSQL_ROOT_PASSWORD: root
# #     ports:
# #       - "8081:80"
# #     depends_on:
# #       - mysql
# #     networks:
# #       - backend

# #   app:
# #     build: .
# #     container_name: springboot-app
# #     restart: always
# #     depends_on:
# #       - mysql
# #     ports:
# #       - "8080:8080"
# #     environment:
# #       SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/demo_security?useTimezone=true&serverTimezone=America/Sao_Paulo&useSSL=false
# #       SPRING_DATASOURCE_USERNAME: root
# #       SPRING_DATASOURCE_PASSWORD: root
# #     networks:
# #       - backend

# # volumes:
# #   mysql_data:

# # networks:
# #   backend:

# #postgres
# version: "3.8"

# services:
#   postgres:
#     image: postgres:15
#     container_name: postgres-spring-security
#     restart: always
#     environment:
#       POSTGRES_DB: spring_security
#       POSTGRES_USER: root
#       POSTGRES_PASSWORD: root
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - backend

#   pgadmin:
#     image: dpage/pgadmin4
#     container_name: pgadmin_spring-security
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@admin.com
#       PGADMIN_DEFAULT_PASSWORD: admin
#     ports:
#       - "15432:80"
#     networks:
#       - backend

#   app:
#     build: .
#     container_name: spring_security-app
#     restart: always
#     depends_on:
#       - postgres
#     ports:
#       - "8080:8080"
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/spring_security
#       SPRING_DATASOURCE_USERNAME: root
#       SPRING_DATASOURCE_PASSWORD: root
#     networks:
#       - backend

# volumes:
#   postgres_data:

# networks:
#   backend:

# version: "3"
# services:
#   db:
#     image: postgres:9.6
#     restart: always
#     environment:
#       POSTGRES_PASSWORD: root
#       POSTGRES_DB: spring_security
#     ports:
#       - 5435:5432
#     volumes:
#       - ./postgres-data:/bitnami/postgresql/data

services:
  app:
    build: .
    container_name: spring_security-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/spring_security
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - backend

networks:
  backend:
